---
title: "R Notebook"
output: html_notebook
---

```{r}
library(h2o)
library(tidyverse)
library(janitor)
```

```{r}
red_file = 'winequality-red.csv'
white_file = 'winequality-white.csv'
base_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/'

red_wine <- read_delim(
  paste0(base_url, red_file), delim = ";", escape_double = FALSE, trim_ws = TRUE
)

#write_csv(red_wine, "red_wine.csv")

white_wine <- read_delim(
  paste0(base_url, white_file), delim = ";", escape_double = FALSE, trim_ws = TRUE
)

#write_csv(white_wine, "white_wine.csv")
```

```{r}
wine_df <- bind_rows(red_wine, white_wine) %>%
  clean_names() %>%
  mutate(
    wine_class = ifelse(quality >= 7, "IdDrinkThat", "NoThanks")
    ) %>%
  mutate(wine_class = as.factor(wine_class)) %>%
  select(-quality)
```


```{r}
trainTestSplit <- function(df, split_proportion) {
  set.seed(123)
  out_list <- list()
  data_split <- sample(
    1:2,
    size = nrow(df),
    prob = split_proportion,
    replace = TRUE
  )

  out_list$train <- df[data_split == 1, ]
  out_list$test <- df[data_split == 2, ]
  return(out_list)
}
```

```{r}
split_proportion <- c(0.7, 0.3)
df_split <- trainTestSplit(wine_df, split_proportion)
```

```{r}
h2o.init(nthreads = -1)
train_h2o <- as.h2o(df_split$train)
test_h2o <- as.h2o(df_split$test)
y_var <- "wine_class"
x_var <- setdiff(names(train_h2o), y_var)

gbm_fit = h2o.gbm(
  x = x_var, 
  y = y_var,
  distribution = "bernoulli",
  training_frame = train_h2o,
  stopping_rounds = 3,
  stopping_metric = "AUC",
  verbose = FALSE
  )
```

```{r}
data.frame(gbm_fit@model$variable_importances) %>%
  select(variable, relative_importance) %>% 
  mutate(
    relative_importance = round(relative_importance),
    variable = factor(variable)
    ) %>% 
    mutate(
      variable = fct_reorder(variable, relative_importance, .desc = TRUE)
      ) %>% 
  ggplot(aes(
    x = variable,
    y = relative_importance,
    fill = variable, 
    label = as.character(relative_importance)
    )) + 
    geom_bar(stat = "identity") + 
    geom_label(label.size = 1, size = 5, color = "white") + 
    theme_bw() + 
    theme(legend.position = "none") + 
    ylab("Relative Importance") + 
    xlab("Variable") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12))
```

```{r}
gbm_auc <- h2o.auc(h2o.performance(gbm_fit, newdata = test_h2o))
```


```{r}
rf_fit <- h2o.randomForest(
  x = x_var,
  y = y_var,
  training_frame = train_h2o,
  stopping_rounds = 3,
  stopping_metric = "AUC"
)

rf_auc <- h2o.auc(h2o.performance(rf_fit, newdata = test_h2o))
```

```{r}
nn_fit <- h2o.deeplearning(
  x = x_var,
  y = y_var,
  training_frame = train_h2o,
  stopping_rounds = 3,
  stopping_metric = "AUC"
)

nn_auc <- h2o.auc(h2o.performance(nn_fit, newdata = test_h2o))
```


```{r}
glm_fit <- h2o.glm(
  x = x_var,
  y = y_var,
  family = "binomial",
  training_frame = train_h2o
)

glm_auc <- h2o.auc(h2o.performance(glm_fit, newdata = test_h2o))
```

```{r}
auc_df <- data.frame(
  n_noise_vars = rep(0, 4),
  method = c("gbm", "rf", "nn", "glm"),
  AUC = c(gbm_auc, rf_auc, nn_auc, glm_auc)
) %>%
  arrange(desc(AUC))
```

```{r}
print(round(table(wine_df$wine_class)/nrow(wine_df) * 100, 1))
```

```{r}
n_noise_vars <- seq(100, 2000, length.out = 20)

for (i in n_noise_vars) {
  print(i)
  temp_noise_df_train <- data.frame(placeholder = rep(NA, nrow(df_split$train)))
  temp_noise_df_test <- data.frame(placeholder = rep(NA, nrow(df_split$test)))

  # add in i irrelevant predictors to train and test
  for (j in 1:i) {
    temp_noise_df_train <- cbind(
      temp_noise_df_train,
      data.frame(noise.var = rnorm(
        nrow(df_split$train),
        0,
        1
      ))
    )
    temp_noise_df_test <- cbind(
      temp_noise_df_test,
      data.frame(noise.var = rnorm(
        nrow(df_split$test),
        0,
        1
      ))
    )
  }
  # format names of irrelevant variables
  temp_noise_df_train <- temp_noise_df_train[, 2:dim(temp_noise_df_train)[2]]
  names(temp_noise_df_train) <- gsub("\\.", "", names(temp_noise_df_train))
  temp_noise_df_train <- as.h2o(cbind(
    temp_noise_df_train,
    df_split$train
  ))

  temp_noise_df_test <- temp_noise_df_test[, 2:dim(temp_noise_df_test)[2]]
  names(temp_noise_df_test) <- gsub("\\.", "", names(temp_noise_df_test))
  temp_noise_df_test <- cbind(
    temp_noise_df_test,
    df_split$test
  )

  x_var <- setdiff(names(temp_noise_df_train), y_var)

  gbm_fit <- h2o.gbm(
    x = x_var,
    y = y_var,
    distribution = "bernoulli",
    training_frame = temp_noise_df_train,
    stopping_rounds = 3,
    stopping_metric = "AUC"
  )

  rf_fit <- h2o.randomForest(
    x = x_var,
    y = y_var,
    training_frame = temp_noise_df_train,
    stopping_rounds = 3,
    stopping_metric = "AUC"
  )

  nn_fit <- h2o.deeplearning(
    x = x_var,
    y = y_var,
    training_frame = temp_noise_df_train,
    stopping_rounds = 3,
    stopping_metric = "AUC"
  )

  glm_fit <- h2o.glm(
    x = x_var,
    y = y_var,
    family = "binomial",
    training_frame = temp_noise_df_train
  )

  temp_noise_df_test <- as.h2o(temp_noise_df_test)

  gbm_auc <- h2o.auc(h2o.performance(gbm_fit, newdata = temp_noise_df_test))
  rf_auc <- h2o.auc(h2o.performance(rf_fit, newdata = temp_noise_df_test))
  nn_auc <- h2o.auc(h2o.performance(nn_fit, newdata = temp_noise_df_test))
  glm_auc <- h2o.auc(h2o.performance(glm_fit, newdata = temp_noise_df_test))

  auc_df <- rbind(
    auc_df,
    data.frame(
      n_noise_vars = i,
      method = c("gbm", "rf", "nn", "glm"),
      AUC = c(gbm_auc, rf_auc, nn_auc, glm_auc)
    )
  )
}
```

```{r}
auc_df %>%
  ggplot(aes(
    x = n_noise_vars, 
    y = AUC, 
    color = method
    )) + 
  geom_point(size = 2) + 
  stat_smooth(span = 1.75, se = FALSE,  size = 2) + 
  theme_bw() + 
  labs(
    x = 'N Noise Variables',
    y = 'AUC'
  )
```

